# Generated by Django 5.2.3 on 2025-07-01 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driving_schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nom')),
                ('cin', models.CharField(max_length=20, unique=True, verbose_name='CIN')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/', verbose_name='Photo')),
                ('date_of_birth', models.DateField(verbose_name='Date de naissance')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('license_type', models.CharField(choices=[('A', 'Permis A (Moto)'), ('B', 'Permis B (Voiture)'), ('C', 'Permis C (Camion)'), ('D', 'Permis D (Bus)')], max_length=1, verbose_name='Type de permis')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('formation_status', models.CharField(choices=[('registered', 'Inscrit'), ('theory_in_progress', 'Code en cours'), ('theory_passed', 'Code réussi'), ('practical_in_progress', 'Conduite en cours'), ('practical_passed', 'Conduite réussie'), ('completed', 'Formation terminée'), ('suspended', 'Suspendu')], default='registered', max_length=30, verbose_name='Statut de formation')),
                ('payment_type', models.CharField(choices=[('fixed', 'Tarif fixe'), ('hourly', 'Par heure')], default='fixed', max_length=10, verbose_name='Type de paiement')),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix fixe')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tarif horaire')),
                ('theory_hours_completed', models.IntegerField(default=0, verbose_name='Heures de code effectuées')),
                ('practical_hours_completed', models.IntegerField(default=0, verbose_name='Heures de conduite effectuées')),
                ('theory_exam_attempts', models.IntegerField(default=0, verbose_name='Tentatives examen code')),
                ('practical_exam_attempts', models.IntegerField(default=0, verbose_name='Tentatives examen conduite')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('driving_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='driving_schools.drivingschool', verbose_name='Auto-école')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Candidat',
                'verbose_name_plural': 'Candidats',
            },
        ),
    ]
