# Generated by Django 5.2.3 on 2025-07-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='paid_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Montant payé (DT)'),
        ),
        migrations.AddField(
            model_name='student',
            name='paid_sessions',
            field=models.IntegerField(default=0, verbose_name='Séances payées'),
        ),
        migrations.AddField(
            model_name='student',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Montant total (DT)'),
        ),
        migrations.AddField(
            model_name='student',
            name='total_sessions',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre total de séances'),
        ),
    ]
