# Generated by Django 5.2.3 on 2025-07-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_paid_amount_student_paid_sessions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='practical_hours_completed',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Heures de conduite effectuées'),
        ),
        migrations.AlterField(
            model_name='student',
            name='theory_hours_completed',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Heures de code effectuées'),
        ),
    ]
