# Generated by Django 5.2.3 on 2025-07-01 07:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrivingSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'auto-école")),
                ('logo', models.ImageField(blank=True, null=True, upload_to='driving_schools/logos/', verbose_name='Logo')),
                ('manager_name', models.CharField(max_length=100, verbose_name='Nom du responsable')),
                ('manager_photo', models.ImageField(blank=True, null=True, upload_to='driving_schools/managers/', verbose_name='Photo du responsable')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('cin_document', models.ImageField(upload_to='driving_schools/documents/cin/', verbose_name='Document CIN')),
                ('legal_documents', models.FileField(upload_to='driving_schools/documents/legal/', verbose_name='Documents légaux')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('suspended', 'Suspendu')], default='pending', max_length=20, verbose_name='Statut')),
                ('current_plan', models.CharField(choices=[('free', 'Gratuit (30 jours)'), ('standard', 'Standard'), ('premium', 'Premium')], default='free', max_length=20, verbose_name='Plan actuel')),
                ('plan_start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de début du plan')),
                ('plan_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin du plan')),
                ('max_accounts', models.IntegerField(default=50, verbose_name='Nombre maximum de comptes')),
                ('current_accounts', models.IntegerField(default=0, verbose_name='Nombre actuel de comptes')),
                ('theme_color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Couleur du thème')),
                ('dark_mode', models.BooleanField(default=False, verbose_name='Mode sombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driving_school', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Auto-école',
                'verbose_name_plural': 'Auto-écoles',
            },
        ),
    ]
