# Generated by Django 5.2.3 on 2025-07-01 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_schools', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('rent', 'Loyer'), ('utilities', 'Charges'), ('insurance', 'Assurance'), ('fuel', 'Carburant'), ('maintenance', 'Maintenance'), ('salaries', 'Salaires'), ('marketing', 'Marketing'), ('equipment', 'Équipement'), ('training', 'Formation'), ('administrative', 'Administratif'), ('other', 'Autre')], max_length=20, verbose_name='Catégorie')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('date', models.DateField(verbose_name='Date')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='expenses/receipts/', verbose_name='Reçu')),
                ('supplier', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fournisseur')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de référence')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Récurrent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('driving_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='driving_schools.drivingschool', verbose_name='Auto-école')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('student_fees', 'Frais étudiants'), ('exam_fees', "Frais d'examens"), ('additional_services', 'Services supplémentaires'), ('other', 'Autre')], max_length=20, verbose_name='Source')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('date', models.DateField(verbose_name='Date')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de référence')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('driving_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='driving_schools.drivingschool', verbose_name='Auto-école')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_revenues', to='students.student', verbose_name='Candidat')),
            ],
            options={
                'verbose_name': 'Revenu',
                'verbose_name_plural': 'Revenus',
                'ordering': ['-date'],
            },
        ),
    ]
