# Generated by Django 5.2.3 on 2025-07-10 09:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_schools', '0002_expense_revenue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UpgradeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_plan', models.CharField(choices=[('free', 'Gratuit (30 jours)'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=20, verbose_name='Plan actuel')),
                ('requested_plan', models.CharField(choices=[('free', 'Gratuit (30 jours)'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=20, verbose_name='Plan demandé')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Virement bancaire'), ('card', 'Carte bancaire'), ('flouci', 'Flouci')], max_length=20, verbose_name='Méthode de paiement')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notes administrateur')),
                ('driving_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_requests', to='driving_schools.drivingschool', verbose_name='Auto-école')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_upgrades', to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
            ],
            options={
                'verbose_name': 'Demande de mise à niveau',
                'verbose_name_plural': 'Demandes de mise à niveau',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_file', models.FileField(upload_to='payment_proofs/', verbose_name='Justificatif de paiement')),
                ('transfer_reference', models.CharField(blank=True, max_length=100, verbose_name='Référence du virement')),
                ('transfer_date', models.DateField(blank=True, null=True, verbose_name='Date du virement')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('upgrade_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proof', to='driving_schools.upgraderequest', verbose_name='Demande de mise à niveau')),
            ],
            options={
                'verbose_name': 'Justificatif de paiement',
                'verbose_name_plural': 'Justificatifs de paiement',
            },
        ),
    ]
