# Generated by Django 5.2.3 on 2025-07-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_schools', '0003_upgraderequest_paymentproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivingschool',
            name='renewal_count',
            field=models.IntegerField(default=0, verbose_name='Nombre de renouvellements'),
        ),
        migrations.AddField(
            model_name='upgraderequest',
            name='is_renewal',
            field=models.BooleanField(default=False, verbose_name='Renouvellement'),
        ),
    ]
