# Generated by Django 5.2.3 on 2025-07-11 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driving_schools', '0002_add_renewal_fields'),
        ('driving_schools', '0004_drivingschool_renewal_count_and_more'),
    ]

    operations = [
    ]
