# Generated by Django 5.2.3 on 2025-07-11 11:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_schools', '0005_merge_20250711_1221'),
        ('vehicles', '0003_merge_0002_delete_vehicleexpense_0002_vehicle_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('fuel', 'Carburant'), ('maintenance', 'Entretien'), ('repair', 'Réparation'), ('insurance', 'Assurance'), ('inspection', 'Visite technique'), ('other', 'Autre')], max_length=20, verbose_name='Catégorie')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (DT)')),
                ('date', models.DateField(verbose_name='Date')),
                ('odometer_reading', models.IntegerField(blank=True, null=True, verbose_name='Kilométrage')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='vehicle_receipts/', verbose_name='Reçu/Facture')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('driving_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_expenses', to='driving_schools.drivingschool', verbose_name='Auto-école')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='vehicles.vehicle', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Dépense véhicule',
                'verbose_name_plural': 'Dépenses véhicules',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountingEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('expense', 'Dépense'), ('revenue', 'Recette')], max_length=20, verbose_name='Type')),
                ('category', models.CharField(max_length=50, verbose_name='Catégorie')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (DT)')),
                ('date', models.DateField(verbose_name='Date')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='accounting_receipts/', verbose_name='Justificatif')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('driving_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_entries', to='driving_schools.drivingschool', verbose_name='Auto-école')),
                ('vehicle_expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounting_entry', to='driving_schools.vehicleexpense', verbose_name='Dépense véhicule liée')),
            ],
            options={
                'verbose_name': 'Écriture comptable',
                'verbose_name_plural': 'Écritures comptables',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
