# Generated by Django 5.2.3 on 2025-07-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_schools', '0006_vehicleexpense_accountingentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivingschool',
            name='license_number',
            field=models.CharField(blank=True, default='', help_text="Numéro d'agrément officiel de l'auto-école", max_length=50, verbose_name="Numéro d'agrément"),
        ),
    ]
