# Generated by Django 5.2.3 on 2025-07-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_schools', '0007_drivingschool_license_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivingschool',
            name='license_number',
            field=models.CharField(blank=True, default='', help_text="Numéro d'agrément ou de licence de l'auto-école", max_length=100, verbose_name="Numéro d'agrément"),
        ),
    ]
