# Generated by Django 5.2.3 on 2025-07-16 12:01

from django.db import migrations, models


def update_free_plans_to_standard(apps, schema_editor):
    """Convertir tous les plans 'free' en 'standard'"""
    DrivingSchool = apps.get_model('driving_schools', 'DrivingSchool')
    UpgradeRequest = apps.get_model('driving_schools', 'UpgradeRequest')

    # Mettre à jour les auto-écoles
    DrivingSchool.objects.filter(current_plan='free').update(
        current_plan='standard',
        max_accounts=10
    )

    # Mettre à jour les demandes de mise à niveau
    UpgradeRequest.objects.filter(current_plan='free').update(current_plan='standard')
    UpgradeRequest.objects.filter(requested_plan='free').update(requested_plan='standard')

    print("✅ Conversion des plans 'free' vers 'standard' terminée")


def reverse_update_free_plans_to_standard(apps, schema_editor):
    """Fonction de retour (optionnelle)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('driving_schools', '0008_alter_drivingschool_license_number'),
    ]

    operations = [
        # D'abord exécuter la migration de données
        migrations.RunPython(
            update_free_plans_to_standard,
            reverse_update_free_plans_to_standard
        ),
        migrations.AlterField(
            model_name='drivingschool',
            name='current_plan',
            field=models.CharField(choices=[('standard', 'Standard (30 jours gratuits)'), ('premium', 'Premium')], default='standard', max_length=20, verbose_name='Plan actuel'),
        ),
        migrations.AlterField(
            model_name='drivingschool',
            name='max_accounts',
            field=models.IntegerField(default=10, verbose_name='Nombre maximum de comptes'),
        ),
        migrations.AlterField(
            model_name='upgraderequest',
            name='current_plan',
            field=models.CharField(choices=[('standard', 'Standard (30 jours gratuits)'), ('premium', 'Premium')], max_length=20, verbose_name='Plan actuel'),
        ),
        migrations.AlterField(
            model_name='upgraderequest',
            name='requested_plan',
            field=models.CharField(choices=[('standard', 'Standard (30 jours gratuits)'), ('premium', 'Premium')], max_length=20, verbose_name='Plan demandé'),
        ),
    ]
