# Generated by Django 5.2.3 on 2025-07-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_schools', '0009_update_plan_to_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivingschool',
            name='current_plan',
            field=models.CharField(choices=[('standard', 'Standard (30 jours gratuits)'), ('premium', 'Premium')], default='standard', help_text='Ancien système de plans - sera supprimé', max_length=20, verbose_name='Plan actuel (legacy)'),
        ),
    ]
