# Generated by Django 5.2.3 on 2025-07-13 18:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_student', 'Nouveau étudiant inscrit'), ('instructor_update', 'Mise à jour moniteur'), ('vehicle_issue', 'Problème véhicule'), ('payment_received', 'Paiement reçu'), ('payment_overdue', 'Paiement en retard'), ('session_assigned', 'Nouvelle séance assignée'), ('schedule_change', "Changement d'horaire"), ('student_progress', 'Progrès étudiant'), ('session_cancelled', 'Séance annulée'), ('lesson_confirmed', 'Leçon confirmée'), ('lesson_reminder', 'Rappel de leçon'), ('schedule_updated', 'Horaire mis à jour'), ('exam_result', "Résultat d'examen"), ('payment_reminder', 'Rappel de paiement'), ('payment_confirmed', 'Paiement confirmé')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée'), ('urgent', 'Urgente')], default='medium', max_length=10)),
                ('related_student_id', models.IntegerField(blank=True, null=True)),
                ('related_instructor_id', models.IntegerField(blank=True, null=True)),
                ('related_session_id', models.IntegerField(blank=True, null=True)),
                ('related_vehicle_id', models.IntegerField(blank=True, null=True)),
                ('related_payment_id', models.IntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_f39341_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx')],
            },
        ),
    ]
