# Generated by Django 5.2.3 on 2025-07-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_student', 'Nouveau étudiant inscrit'), ('instructor_update', 'Mise à jour moniteur'), ('vehicle_issue', 'Problème véhicule'), ('vehicle_expense', 'Dépense véhicule'), ('payment_received', 'Paiement reçu'), ('payment_overdue', 'Paiement en retard'), ('subscription_expiry', 'Expiration abonnement'), ('vehicle_expiry', 'Expiration véhicule'), ('session_assigned', 'Nouvelle séance assignée'), ('schedule_change', "Changement d'horaire"), ('student_progress', 'Progrès étudiant'), ('session_cancelled', 'Séance annulée'), ('lesson_confirmed', 'Leçon confirmée'), ('lesson_reminder', 'Rappel de leçon'), ('schedule_updated', 'Horaire mis à jour'), ('exam_result', "Résultat d'examen"), ('exam_reminder', "Rappel d'examen"), ('payment_reminder', 'Rappel de paiement'), ('payment_confirmed', 'Paiement confirmé'), ('exam_added', 'Nouvel examen')], max_length=50),
        ),
    ]
