# Generated by Django 5.2.3 on 2025-07-01 07:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driving_schools', '0001_initial'),
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='Matriculation')),
                ('brand', models.CharField(max_length=50, verbose_name='Marque')),
                ('model', models.CharField(max_length=50, verbose_name='Modèle')),
                ('year', models.IntegerField(verbose_name='Année')),
                ('color', models.CharField(max_length=30, verbose_name='Couleur')),
                ('vehicle_type', models.CharField(choices=[('A', 'Moto'), ('B', 'Voiture'), ('C', 'Camion'), ('D', 'Bus')], max_length=1, verbose_name='Type de véhicule')),
                ('engine_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro moteur')),
                ('chassis_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro châssis')),
                ('current_mileage', models.IntegerField(default=0, verbose_name='Kilométrage actuel')),
                ('technical_inspection_date', models.DateField(verbose_name='Date visite technique')),
                ('insurance_expiry_date', models.DateField(verbose_name='Date expiration assurance')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('maintenance', 'En maintenance'), ('inactive', 'Inactif')], default='active', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('assigned_instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicles', to='instructors.instructor', verbose_name='Moniteur assigné')),
                ('driving_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='driving_schools.drivingschool', verbose_name='Auto-école')),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
            },
        ),
        migrations.CreateModel(
            name='VehicleExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('fuel', 'Carburant'), ('maintenance', 'Maintenance'), ('repair', 'Réparation'), ('insurance', 'Assurance'), ('technical_inspection', 'Visite technique'), ('other', 'Autre')], max_length=20, verbose_name='Type de dépense')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('fuel_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Quantité carburant (L)')),
                ('mileage_at_expense', models.IntegerField(blank=True, null=True, verbose_name='Kilométrage lors de la dépense')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='vehicles.vehicle', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Dépense véhicule',
                'verbose_name_plural': 'Dépenses véhicules',
                'ordering': ['-date'],
            },
        ),
    ]
