# Generated by Django 5.2.3 on 2025-07-11 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_delete_vehicleexpense'),
        ('vehicles', '0002_vehicle_photo'),
    ]

    operations = [
    ]
