# Generated by Django 5.2.3 on 2025-07-01 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driving_schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nom')),
                ('cin', models.CharField(max_length=20, unique=True, verbose_name='CIN')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='instructors/photos/', verbose_name='Photo')),
                ('license_types', models.CharField(max_length=10, verbose_name='Types de permis')),
                ('hire_date', models.DateField(verbose_name="Date d'embauche")),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('driving_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='driving_schools.drivingschool', verbose_name='Auto-école')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Moniteur',
                'verbose_name_plural': 'Moniteurs',
            },
        ),
    ]
