# Generated by Django 5.2.3 on 2025-07-01 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driving_schools', '0002_expense_revenue'),
        ('instructors', '0001_initial'),
        ('students', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('theory', 'Code'), ('practical', 'Conduite'), ('exam_theory', 'Examen Code'), ('exam_practical_circuit', 'Examen Circuit'), ('exam_practical_park', 'Examen Parking')], max_length=25, verbose_name='Type de séance')),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('end_time', models.TimeField(verbose_name='Heure de fin')),
                ('status', models.CharField(choices=[('scheduled', 'Programmé'), ('completed', 'Terminé'), ('cancelled', 'Annulé'), ('no_show', 'Absent')], default='scheduled', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('cancellation_reason', models.TextField(blank=True, null=True, verbose_name="Raison d'annulation")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('driving_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='driving_schools.drivingschool', verbose_name='Auto-école')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='instructors.instructor', verbose_name='Moniteur')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='students.student', verbose_name='Candidat')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='vehicles.vehicle', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Séance',
                'verbose_name_plural': 'Séances',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
