# Generated by Django 5.2.3 on 2025-07-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_recreate_admin_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactionlog',
            name='target_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adminactionlog',
            name='target_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
