# Generated by Django 5.2.3 on 2025-07-01 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driving_schools', '0002_expense_revenue'),
        ('instructors', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('theory', 'Code de la route'), ('practical_circuit', 'Circuit'), ('practical_park', 'Parking')], max_length=20, verbose_name="Type d'examen")),
                ('exam_date', models.DateTimeField(verbose_name="Date et heure d'examen")),
                ('exam_location', models.CharField(blank=True, max_length=200, null=True, verbose_name="Lieu d'examen")),
                ('result', models.CharField(choices=[('pending', 'En attente'), ('passed', 'Réussi'), ('failed', 'Échoué'), ('absent', 'Absent')], default='pending', max_length=20, verbose_name='Résultat')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Score')),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Score maximum')),
                ('examiner_notes', models.TextField(blank=True, null=True, verbose_name="Notes de l'examinateur")),
                ('student_feedback', models.TextField(blank=True, null=True, verbose_name='Commentaires du candidat')),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True, verbose_name="Numéro d'inscription")),
                ('exam_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Frais d'examen")),
                ('is_paid', models.BooleanField(default=False, verbose_name='Payé')),
                ('attempt_number', models.IntegerField(default=1, verbose_name='Numéro de tentative')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('driving_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='driving_schools.drivingschool', verbose_name='Auto-école')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_exams', to='instructors.instructor', verbose_name='Moniteur superviseur')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='students.student', verbose_name='Candidat')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Examens',
                'ordering': ['-exam_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=200, verbose_name='Nom de la session')),
                ('exam_type', models.CharField(choices=[('theory', 'Code de la route'), ('practical_circuit', 'Circuit'), ('practical_park', 'Parking')], max_length=20, verbose_name="Type d'examen")),
                ('session_date', models.DateTimeField(verbose_name='Date de la session')),
                ('location', models.CharField(max_length=200, verbose_name='Lieu')),
                ('max_candidates', models.IntegerField(default=20, verbose_name='Nombre maximum de candidats')),
                ('registration_deadline', models.DateTimeField(verbose_name="Date limite d'inscription")),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('driving_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='driving_schools.drivingschool', verbose_name='Auto-école')),
            ],
            options={
                'verbose_name': "Session d'examen",
                'verbose_name_plural': "Sessions d'examens",
                'ordering': ['-session_date'],
            },
        ),
    ]
