# Generated by Django 5.2.3 on 2025-07-01 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driving_schools', '0002_expense_revenue'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('registration', 'Inscription'), ('monthly', 'Mensuel'), ('lesson', 'Séance'), ('exam', 'Examen'), ('additional', 'Supplément')], max_length=20, verbose_name='Type de paiement')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('due_date', models.DateField(verbose_name="Date d'échéance")),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('overdue', 'En retard'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Espèces'), ('bank_transfer', 'Virement bancaire'), ('check', 'Chèque'), ('online', 'Paiement en ligne')], max_length=20, null=True, verbose_name='Méthode de paiement')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de référence')),
                ('receipt_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de reçu')),
                ('theory_hours', models.IntegerField(default=0, verbose_name='Heures de code')),
                ('practical_hours', models.IntegerField(default=0, verbose_name='Heures de conduite')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('driving_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='driving_schools.drivingschool', verbose_name='Auto-école')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.student', verbose_name='Candidat')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium')], max_length=20, verbose_name='Type de plan')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('billing_period_start', models.DateField(verbose_name='Début de période')),
                ('billing_period_end', models.DateField(verbose_name='Fin de période')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20, verbose_name='Statut')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Virement bancaire'), ('online', 'Paiement en ligne')], max_length=20, verbose_name='Méthode de paiement')),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='ID de transaction')),
                ('payment_proof', models.FileField(blank=True, null=True, upload_to='payments/proofs/', verbose_name='Preuve de paiement')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('driving_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='driving_schools.drivingschool', verbose_name='Auto-école')),
            ],
            options={
                'verbose_name': "Paiement d'abonnement",
                'verbose_name_plural': "Paiements d'abonnements",
                'ordering': ['-created_at'],
            },
        ),
    ]
