# Generated by Django 5.2.3 on 2025-07-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='session_count',
            field=models.IntegerField(default=0, verbose_name='Nombre de séances'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('registration', 'Inscription'), ('monthly', 'Mensuel'), ('lesson', 'Séance'), ('exam', 'Examen'), ('additional', 'Supplément'), ('fixed_payment', 'Paiement fixe'), ('session_payment', 'Paiement par séances')], max_length=20, verbose_name='Type de paiement'),
        ),
    ]
