# Generated by Django 5.2.3 on 2025-07-16 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_schools', '0010_alter_drivingschool_current_plan'),
        ('payments', '0003_paymentlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlouciPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('flouci_token', models.CharField(max_length=100, unique=True, verbose_name='Token Flouci')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('success', 'Réussi'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('upgrade_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flouci_payment', to='driving_schools.upgraderequest', verbose_name="Demande d'upgrade")),
            ],
            options={
                'verbose_name': 'Paiement Flouci',
                'verbose_name_plural': 'Paiements Flouci',
                'ordering': ['-created_at'],
            },
        ),
    ]
